[package]
edition = "2024"
name = "imac-5k-control"
version = "0.1.0"
authors = ["Andre Braga Reis <andre@saltwing.com>"]
publish = false

[[bin]]
name = "imac-5k-control"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
critical-section = "1.2.0"
embassy-futures = "0.1.1"
embassy-sync = "0.7.0"
embassy-executor = { version = "0.7.0", features = ["task-arena-size-32768"] }
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
esp-alloc = "0.7.0"
esp-backtrace = { version = "0.15.1", features = [
    "esp32c6",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "1.0.0-beta.0", features = ["esp32c6", "unstable"] }
esp-hal-embassy = { version = "0.7.0", features = ["esp32c6"] }
esp-println = { version = "0.13.0", default-features = false, features = [
    "colors",
    "critical-section",
    "esp32c6",
    # Force JTAG output even if USB is not connected, otherwise it clobbers UART0.
    "jtag-serial",
] }
anyhow = { version = "1.0.98", default-features = false }
crc = "3.3.0"
const_format = { version = "0.2.34", features = ["fmt", "rust_1_83"] }
noline = { version = "0.5.1", features = ["alloc"] }

[profile.dev]
opt-level = "s"

[profile.release]
# LLVM can perform better optimizations using a single thread.
codegen-units = 1
# Amount of debug information included, reduce if low on space.
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
# opt-level 2 or 3 is required for WiFi.
# opt-level 3 codegen is sometimes bonkers.
# opt-level 's' optimized for size.
opt-level = 2
overflow-checks = false
