[toolchain]
# channel = "stable"
# channel = "nightly-2025-03-28"            # ~1.87.0
# channel = "nightly-2025-05-09"            # ~1.88.0
# channel = "nightly-2025-09-12"            # ~1.91.0
channel = "nightly-2025-12-05"            # ~1.93.0
components = ["rust-src"]
targets = ["riscv32imac-unknown-none-elf"]
