[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[env]
ESP_WIFI_CONFIG_COUNTRY_CODE = "NZ"
# ESP_WIFI_CONFIG_RX_QUEUE_SIZE = 5
# ESP_WIFI_CONFIG_TX_QUEUE_SIZE = 3
# ESP_WIFI_CONFIG_MAX_BURST_SIZE = 1

# Keeps USB running when using WiFi. This allows debugging and log
# messages via USB Serial JTAG. Turn off for best WiFi performance.
#
# Warning: when disabled, boot pin must be held low to flash (use button or pin).
# ESP_WIFI_CONFIG_PHY_ENABLE_USB = "false"

[build]
rustflags = [
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: Not required if using "panic-halt".
    # NOTE: May negatively impact performance of produced code.
  "-C", "force-frame-pointers",
  "-Z", "stack-protector=all",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
